"use client";

import { ArrowRight, Check, GitPullRequest, CreditCard, KeyRound, AlertTriangle, ArrowUpRight, CircleCheck, Waves, Terminal, Clock3, Plus } from "lucide-react";
import { useStore } from "./store";
import { Avatar, Badge, Progress, SectionTitle, TextLink, timeLabel } from "./ui";
export type Selection = { type: "approval" | "goal" | "task" | "worker" | "incident" | "file" | "connector"; id: string };
export type Screen = "Overview" | "Goals" | "Work" | "People" | "Approvals" | "Activity" | "Systems" | "Files" | "AI" | "Settings";
export type ViewProps = { open: (selection: Selection) => void; navigate: (screen: Screen) => void; newGoal: () => void; command: () => void };

export function Overview({ open, navigate, newGoal, command }: ViewProps) {
  const { state } = useStore();
  const pending = state.approvals.filter(a => a.status === "pending");
  const incidents = state.incidents.filter(i => i.status !== "resolved");
  const blocked = state.tasks.filter(t => t.status === "blocked");
  const running = state.tasks.filter(t => t.status === "running");
  const completed = state.tasks.filter(t => t.status === "completed");
  const goals = state.goals.filter(g => g.status !== "completed");
  const attention = pending.length + incidents.length + blocked.length;
  return <>
    <div className="page-intro"><div><p className="eyebrow">YOUR ORGANIZATION. IN FOCUS.</p><h1>Good morning, Amey<span className="muted">.</span></h1><p className="intro-copy">Waves is moving. <span>{attention ? `${attention} things need your attention.` : "Nothing needs your attention."}</span></p></div><button className="button primary" onClick={newGoal}><Plus size={16} /> New goal</button></div>
    <div className="overview-layout"><div className="overview-main">
      <section><SectionTitle title="NEEDS YOU" count={attention}><span className="section-note">Your judgment. Their next move.</span></SectionTitle>
        <div className="attention-stack">
          {pending.map((approval, index) => <article className={`attention-card ${index === 0 ? "featured" : ""}`} key={approval.id}><div className="attention-icon">{approval.kind === "deployment" ? <GitPullRequest size={19} /> : approval.kind === "payment" ? <CreditCard size={19} /> : <KeyRound size={19} />}</div><div className="attention-content"><div className="card-eyebrow"><span>{approval.project}</span><Badge tone="warning">Approval needed</Badge></div><h3>{approval.title}</h3>{approval.kind === "deployment" ? <div className="evidence-inline">{approval.evidence.slice(0, 3).map((evidence, i) => <span key={i}>{/passed/i.test(evidence) && <Check size={12} />}{evidence}</span>)}</div> : <p>{approval.kind === "payment" ? `Infrastructure upgrade · ${approval.cost}` : approval.what}</p>}<div className="card-foot"><span><Waves size={12} /> {approval.requestedBy} <span className="dot-separator">·</span> Ready for your decision</span><button className={`button small ${index === 0 ? "primary" : ""}`} onClick={() => open({ type: "approval", id: approval.id })}>Review<ArrowUpRight size={14} /></button></div></div></article>)}
          {incidents.map(incident => <article key={incident.id} className="attention-card compact"><div className={`attention-icon ${incident.severity === "error" ? "error-text" : "warning-text"}`}><AlertTriangle size={18} /></div><div className="attention-content"><div className="card-eyebrow"><span>{incident.project}</span><Badge tone={incident.severity === "error" ? "error" : "warning"}>{incident.severity === "error" ? "Production error" : "Warning"}</Badge></div><div className="attention-bottom"><div><h3>{incident.title}</h3><p>{incident.impact}</p></div><button className="icon-button bordered" aria-label={`View ${incident.title}`} onClick={() => open({ type: "incident", id: incident.id })}><ArrowUpRight size={17} /></button></div></div></article>)}
          {blocked.map(task => <article className="attention-card compact" key={task.id}><div className="attention-icon warning-text"><Clock3 size={18} /></div><div className="attention-content"><div className="card-eyebrow"><span>Engineering</span><Badge tone="warning">Blocked</Badge></div><div className="attention-bottom"><div><h3>{task.owner} needs a hand</h3><p>{task.title} · Waiting for API credentials</p></div><button className="icon-button bordered" aria-label={`Resolve ${task.title}`} onClick={() => open({ type: "task", id: task.id })}><ArrowUpRight size={17} /></button></div></div></article>)}
          {!attention && <div className="all-clear"><CircleCheck size={24} /><h3>You’re all clear.</h3><p>The organization has what it needs. Set the next direction.</p></div>}
        </div>
      </section>
      <section><SectionTitle title="IN MOTION" count={running.length}><TextLink onClick={() => navigate("Work")}>All work</TextLink></SectionTitle><div className="list-panel">{running.slice(0, 3).map(task => <button className="motion-row" key={task.id} onClick={() => open({ type: "task", id: task.id })}><span className="task-indicator"><span /></span><div className="row-main"><strong>{task.title}</strong><span>{task.project} <span className="dot-separator">/</span> {task.owner}</span></div><span className="motion-state">Running</span><ArrowUpRight size={15} /></button>)}{running.length === 0 && <p className="panel-padding muted">No tasks are running. Delegate an active goal to begin.</p>}</div></section>
      <section><SectionTitle title="ACTIVE GOALS" count={goals.length}><TextLink onClick={() => navigate("Goals")}>All goals</TextLink></SectionTitle><div className="goal-grid">{goals.slice(0, 4).map(goal => { const tasks = state.tasks.filter(t => t.goalId === goal.id); const done = tasks.filter(t => t.status === "completed").length; const percent = tasks.length ? Math.round(done / tasks.length * 100) : 0; return <button className="goal-card" key={goal.id} onClick={() => open({ type: "goal", id: goal.id })}><div className="goal-top"><span className="project-mark">{goal.project.slice(0, 2).toUpperCase()}</span><ArrowUpRight size={16} /></div><h3>{goal.title}</h3><p>{tasks.length} tasks <span className="dot-separator">·</span> {goal.deadline}</p><div className="progress-label"><span>{done} of {tasks.length} complete</span><span>{percent}%</span></div><Progress value={percent} /></button>; })}</div></section>
      <section className="recent-completions"><SectionTitle title="RECENTLY COMPLETED" count={completed.length} /><div className="list-panel">{completed.slice(0, 3).map(task => <button className="motion-row" onClick={() => open({ type: "task", id: task.id })} key={task.id}><CircleCheck size={17} className="success-text" /><div className="row-main"><strong>{task.title}</strong><span>{task.owner} · {task.project}</span></div><ArrowUpRight size={15} /></button>)}</div></section>
    </div><aside className="overview-rail">
      <section className="brief-panel"><div className="brief-heading"><span className="eyebrow">DAILY BRIEF</span><span className="mono">17 SEP</span></div><h3>A clear view.<br /><span className="muted">A focused day.</span></h3><div className="brief-stats">{[[completed.length, "Completed"], [running.length, "In progress"], [blocked.length, "Blocked"], [pending.length, "Needs approval"]].map(([number, label]) => <div key={label}><strong>{String(number).padStart(2, "0")}</strong><span>{label}</span></div>)}</div><div className="brief-note"><span className="status-dot error" />{incidents.filter(i => i.severity === "error").length} critical incident{incidents.filter(i => i.severity === "error").length === 1 ? "" : "s"}<button aria-label="View system incidents" onClick={() => navigate("Systems")}><ArrowRight size={14} /></button></div><button className="button full" onClick={command}><Waves size={16} />Ask WAVES AI<ArrowUpRight size={14} /></button></section>
      <section><SectionTitle title="LIVE ACTIVITY"><span className="live-label"><span className="status-dot success" />DEMO</span></SectionTitle><div className="timeline">{state.activity.slice(0, 5).map(event => <button className="timeline-event" key={event.id} onClick={() => navigate("Activity")}><span className={`timeline-dot ${event.severity}`} /><time>{timeLabel(event.timestamp)}</time><p><strong>{event.actor}</strong> {event.action.charAt(0).toLowerCase() + event.action.slice(1)}.</p><span className="event-project">{event.project || event.target}</span></button>)}</div><TextLink onClick={() => navigate("Activity")}>View all activity</TextLink></section>
      <section><SectionTitle title="PEOPLE AT WORK"><TextLink onClick={() => navigate("People")}>Team</TextLink></SectionTitle><div className="people-mini">{state.workers.filter(w => w.status === "active").slice(0, 3).map(worker => <button key={worker.id} onClick={() => open({ type: "worker", id: worker.id })}><Avatar initials={worker.initials} agent={worker.type === "AI agent"} /><span><strong>{worker.name}</strong><small>{state.tasks.find(t => t.id === worker.taskId)?.title || worker.role}</small></span><span className="status-dot success" /></button>)}</div></section>
      <button className="agent-summary" onClick={() => navigate("AI")}><span className="agent-summary-icon"><Terminal size={20} /></span><div><strong>Computer agent</strong><span>{state.agentPaused ? "Paused · waiting for direction" : "Standing by · supervised mode"}</span></div><ArrowUpRight size={14} /></button>
      <p className="rail-footer">YOU GIVE DIRECTION. WAVES EXECUTES.</p>
    </aside></div>
  </>;
}
